const themes = [
  {
    id: "0",
    title: 'Bounty Hunter',
    prompt: "RAW photo of (Dog the bounty hunter) as a (dog-man hybrid), 8k",
    neg_prompt: "cropped, off-center, cartoon, 3d model, blurry, smooth skin",
    url: "images/bountyhunter.png",
    type: "image",
    Model: 'animalHumanHybrids_v10',
    CFG_scale: '7',
    Steps: '20',
    Sampler: 'Euler a',
    Seed: '394329227',
    Clip_skip: '2',
  },
  {
    id: "1",
    title: 'Pilot',
    prompt: "a photo of a cat-woman hybrid as a pilot, 8k",
    neg_prompt: "cartoon, 3d model, smooth skin",
    url: "images/pilot.png",
    type: "image",
    Model: '',
    CFG_scale: '7',
    Steps: '32',
    Sampler: 'Euler',
    Seed: '509198318',
    Clip_skip: '',
  },
  {
    id: "2",
    title: 'Business',
    prompt: "a photo of a rhino-woman hybrid as a business-woman, 8k",
    neg_prompt: "cartoon, 3d model, smooth skin",
    url: "images/business.png",
    type: "image",
    Model: '',
    CFG_scale: '7',
    Steps: '32',
    Sampler: 'Euler',
    Seed: '2318110491',
    Clip_skip: '',
  },
  {
    id: "3",
    title: 'Pirate',
    prompt: "a photo of a [cute young fox-girl hybrid|fox-woman hybrid] as a pirate, 8k",
    neg_prompt: "cartoon, 3d model, smooth skin",
    url: "images/pirate.png",
    type: "image",
    Model: '',
    CFG_scale: '7',
    Steps: '30',
    Sampler: 'Euler',
    Seed: '3462186669',
    Clip_skip: '',
  },
  {
    id: "4",
    title: 'Cute',
    prompt: "a photo of a cute mouse-boy hybrid as boy, 8k",
    neg_prompt: "cartoon, 3d model, smooth skin",
    url: "images/cute.png",
    type: "image",
    Model: '',
    CFG_scale: '8.5',
    Steps: '32',
    Sampler: 'Euler',
    Seed: '3059344164',
    Clip_skip: '',
  },
  {
    id: "5",
    title: 'Student',
    prompt: "a photo of a cute hedgehog-girl hybrid as a student-girl, 8k",
    neg_prompt: "cartoon, 3d model, smooth skins.",
    url: "images/student.png",
    type: "image",
    Model: '',
    CFG_scale: '7',
    Steps: '32',
    Sampler: 'Euler',
    Seed: '3378608043',
    Clip_skip: '',
  },
];

export default themes;
